services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - monitoring

  mysqld-exporter:
    image: prom/mysqld-exporter:v0.17.2
    container_name: mysqld_exporter
    environment:
      DATA_SOURCE_NAME: "exporter:exporterpass@(mysql:3306)/"
    depends_on:
      - mysql
    ports:
      - "9104:9104"
    volumes:
      - ./my.cnf:/.my.cnf:ro
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - mysqld-exporter
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    logging:
      driver: "none"

  proxysql:
    image: proxysql/proxysql:latest
    container_name: proxysql
    ports:
      - "6032:6032"
      - "6033:6033"
    networks:
      - monitoring
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf:ro

volumes:
  mysql_data:
  grafana_data:

networks:
  monitoring:
