version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: netflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
