version = 0.1

[default.deploy.parameters]
stack_name = "lambda-extensions"
resolve_s3 = true
s3_prefix = "lambda-extensions"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
